global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'monitoring_servers'
    static_configs:
      - targets: ['10.0.1.168:9100']

  - job_name: 'app_servers'
    static_configs:
      - targets: ['10.0.1.233:9100']

  - job_name: 'prometheus_container'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'grafana_container'
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'loki_container'
    static_configs:
      - targets: ['loki:3100']
