Vagrant.configure("2") do |config|

   config.vm.define "db-server" do |db|
           db.vm.box = "gutehall/ubuntu24-04"
           db.vm.hostname = "db-server"
           db.vm.network "public_network", bridge: "Realtek RTL8822BE 802.11ac PCIe Adapter"

                db.vm.provision "shell", inline: <<-SHELL
                  sudo apt-get update
                  sudo apt-get install -y iftop net-tools # mysql-server
                 SHELL
           end


#   config.vm.define "bk-server" do |bk|
#           bk.vm.box = "gutehall/ubuntu24-04"
#           bk.vm.hostname = "backup-server"
#           bk.vm.network "public_network", ip: "192.168.0.110", bridge: "Realtek RTL8822BE 802.11ac PCIe Adapter"
#
#
#   end
end