Vagrant.configure("2") do |config|

   config.vm.define "vm1" do |vm1|
           vm1.vm.box = "ubuntu/xenial64"
           vm1.vm.hostname = "ubuntu-xenial"
           vm1.vm.network "public_network", bridge: "Realtek RTL8822BE 802.11ac PCIe Adapter"
#            vm1.vm.provision "shell", inline: <<-SHELL
#               apt-get update
#               apt-get install -y nginx
#               SHELL
           vm1.vm.provision "shell", path: 'install_packages.sh'
           vm1.disksize.size = "40GB"
           vm1.vm.provider "virtualbox" do |vb|
               vb.memory = "2048"
               vb.cpus = 2
            vm1.vm.synced_folder "./shared", "/vagrant_data"
           end
   end


 config.vm.define "vm2" do |vm2|
      vm2.vm.box = "generic/centos7"
      vm2.vm.hostname = "centos7-02"
       vm2.vm.network "public_network", bridge: "Realtek RTL8822BE 802.11ac PCIe Adapter"
         vm2.vm.provision "shell", path: "install_packages.sh"
         vm2.disksize.size = "40GB"
         vm2.vm.provider "virtualbox" do |vb|
             vb.memory = "2048"
             vb.cpus = 2
        end
    end




end