apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # Розмір, який ви хочете отримати з PV
  storageClassName: ebs-sc  # Ім'я StorageClass
