apiVersion: v1
kind: ConfigMap
metadata:
  name: web-content
data:
  index.html: |
    <html>
    <head><title>HELLO WORLD</title></head>
    <body>
    <h1>HELLO WORLD</h1>
    </body>
    </html>
