---
- name: Set default firewall rules
  ansible.builtin.command: ufw default {{ ufw_default_policy }}

- name: Allow specified ports
  ansible.builtin.ufw:
    rule: allow
    port: "{{ item }}"
  loop: "{{ ufw_allowed_ports }}"

- name: Deny specified ports
  ansible.builtin.ufw:
    rule: deny
    port: "{{ item }}"
  loop: "{{ ufw_denied_ports }}"

- name: Enable UFW
  ansible.builtin.ufw:
    state: enabled
    log: "{{ ufw_logging }}"
